# Generated by Django 5.2 on 2025-04-17 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
